version: '3.0'
services:
  frontend:
    image: qimiaai27da.azurecr.io/frontend:latest
    ports:
      - "3000:3000"
  model:
    image: qimiaai27da.azurecr.io/model:latest
    hostname: model
    environment:
      AZURE_STORAGE_ACCOUNT_NAME: devopsqimiaaidev
      AZURE_CONTAINER_NAME: llm-foundation-models
      AZURE_FILE_PATH: models7b2/ggml-vicuna-7b-q4_0-300523.bin
  webapi:
    image: qimiaai27da.azurecr.io/webapi:latest
    ports:
      - "8000:8000"
    environment:
      ENV: dev
      CLOUD: azure